"""Python helpers for the Unlimited-OCR C inference core."""

from .convert import (
    DryRunPlan,
    SectionPlan,
    TensorPlan,
    build_dry_run_plan,
    filter_plan_tensors,
    write_uocr_model,
)
from .tensor_registry import TensorFamily, TensorProjection
from .ffi import (
    Engine,
    EngineOptions,
    MemoryReport,
    as_c_request,
    candidate_library_paths,
    find_library_path,
    load_library,
)
from .frontend import (
    BOS_TOKEN_ID,
    EOS_TOKEN_ID,
    IMAGE_TOKEN_ID,
    MULTI_PROMPT,
    PAD_TOKEN_ID,
    PRESETS,
    SINGLE_PROMPT,
    ImageView,
    PreparedRequest,
    Preset,
    dynamic_preprocess,
    format_messages_plain,
    load_prepared_fixture,
    load_tokenizer,
    prepare_image,
    prepare_pages,
    prepare_text,
    render_prompt,
    save_prepared_request,
    validate_tokenizer,
)

__all__ = [
    "DryRunPlan",
    "SectionPlan",
    "TensorPlan",
    "build_dry_run_plan",
    "filter_plan_tensors",
    "write_uocr_model",
    "TensorFamily",
    "TensorProjection",
    "Engine",
    "EngineOptions",
    "MemoryReport",
    "as_c_request",
    "candidate_library_paths",
    "find_library_path",
    "load_library",
    "BOS_TOKEN_ID",
    "EOS_TOKEN_ID",
    "IMAGE_TOKEN_ID",
    "MULTI_PROMPT",
    "PAD_TOKEN_ID",
    "PRESETS",
    "SINGLE_PROMPT",
    "ImageView",
    "PreparedRequest",
    "Preset",
    "dynamic_preprocess",
    "format_messages_plain",
    "load_prepared_fixture",
    "load_tokenizer",
    "prepare_image",
    "prepare_pages",
    "prepare_text",
    "render_prompt",
    "save_prepared_request",
    "validate_tokenizer",
]
