#ifndef UOCR_MODEL_CONSTANTS_H
#define UOCR_MODEL_CONSTANTS_H

#include <stdint.h>

#define UOCR_VOCAB_SIZE 129280u
#define UOCR_BPE_VOCAB_SIZE 128000u
#define UOCR_ADDED_TOKEN_COUNT 830u

#define UOCR_TOKEN_BOS 0
#define UOCR_TOKEN_EOS 1
#define UOCR_TOKEN_PAD 2
#define UOCR_TOKEN_IMAGE 128815

#define UOCR_HIDDEN_SIZE 1280u
#define UOCR_DECODER_LAYERS 12u
#define UOCR_ATTENTION_HEADS 10u
#define UOCR_KV_HEADS 10u
#define UOCR_HEAD_DIM 128u
#define UOCR_ROPE_THETA 10000u
#define UOCR_RMS_NORM_EPS 1.0e-6f
#define UOCR_MAX_POSITIONS 32768u
#define UOCR_GENERATED_RING_WINDOW 128u

#define UOCR_GLOBAL_VIEW_SIZE 1024u
#define UOCR_LOCAL_VIEW_SIZE 640u
#define UOCR_VISION_PATCH_SIZE 16u
#define UOCR_DOWNSAMPLE_RATIO 4u
#define UOCR_GLOBAL_GRID_QUERIES 16u
#define UOCR_LOCAL_GRID_QUERIES 10u
#define UOCR_GLOBAL_VISUAL_TOKENS 273u
#define UOCR_GLOBAL_ROW_NEWLINE_TOKENS 272u

#define UOCR_ROUTED_EXPERTS 64u
#define UOCR_MOE_TOP_K 6u
#define UOCR_MOE_EXPERT_INTERMEDIATE 896u
#define UOCR_MOE_SHARED_INTERMEDIATE 1792u
#define UOCR_DENSE_LAYER0_INTERMEDIATE 6848u

#define UOCR_SAM_HIDDEN_SIZE 768u
#define UOCR_SAM_ATTENTION_HEADS 12u
#define UOCR_SAM_HEAD_DIM 64u
#define UOCR_SAM_QKV_SIZE (3u * UOCR_SAM_HIDDEN_SIZE)
#define UOCR_SAM_MLP_RATIO 4u
#define UOCR_SAM_MLP_INTERMEDIATE (UOCR_SAM_MLP_RATIO * UOCR_SAM_HIDDEN_SIZE)
#define UOCR_SAM_BLOCKS 12u
#define UOCR_SAM_WINDOW_SIZE 14u
#define UOCR_SAM_WINDOW_TOKENS (UOCR_SAM_WINDOW_SIZE * UOCR_SAM_WINDOW_SIZE)
#define UOCR_SAM_WINDOW_REL_POS_SIZE (2u * UOCR_SAM_WINDOW_SIZE - 1u)
#define UOCR_SAM_MAX_GRID_SIZE (UOCR_GLOBAL_VIEW_SIZE / UOCR_VISION_PATCH_SIZE)
#define UOCR_SAM_MAX_GRID_TOKENS (UOCR_SAM_MAX_GRID_SIZE * UOCR_SAM_MAX_GRID_SIZE)
#define UOCR_SAM_MAX_REL_POS_SIZE (2u * UOCR_SAM_MAX_GRID_SIZE - 1u)
#define UOCR_SAM_NECK_CHANNELS 256u
#define UOCR_SAM_NECK_KERNEL_SIZE 3u
#define UOCR_SAM_NET_STRIDE 2u
#define UOCR_SAM_NET2_CHANNELS 512u
#define UOCR_SAM_FEATURE_CHANNELS 1024u
#define UOCR_SAM_NET3_CHANNELS UOCR_SAM_FEATURE_CHANNELS
#define UOCR_CLIP_HIDDEN_SIZE 1024u
#define UOCR_CLIP_PRE_LAYERNORM_EPS 1.0e-5f
#define UOCR_CLIP_CLASS_TOKENS 1u
#define UOCR_CLIP_POSITION_GRID UOCR_GLOBAL_GRID_QUERIES
#define UOCR_CLIP_MAX_GRID_SIZE UOCR_GLOBAL_GRID_QUERIES
#define UOCR_CLIP_GLOBAL_TOKENS (UOCR_CLIP_CLASS_TOKENS + UOCR_GLOBAL_GRID_QUERIES * UOCR_GLOBAL_GRID_QUERIES)
#define UOCR_CLIP_LOCAL_TOKENS (UOCR_CLIP_CLASS_TOKENS + UOCR_LOCAL_GRID_QUERIES * UOCR_LOCAL_GRID_QUERIES)
#define UOCR_CLIP_MAX_TOKENS UOCR_CLIP_GLOBAL_TOKENS
#define UOCR_PROJECTOR_IN_SIZE 2048u

#define UOCR_DEFAULT_MAX_BATCH 1u
#define UOCR_DEFAULT_MAX_PROMPT_TOKENS 4096u
#define UOCR_DEFAULT_MAX_GEN_TOKENS 512u

static inline uint32_t uocr_global_visual_token_count(void) {
    return UOCR_GLOBAL_VISUAL_TOKENS;
}

static inline uint32_t uocr_local_visual_token_count(uint32_t grid_w, uint32_t grid_h) {
    return (UOCR_LOCAL_GRID_QUERIES * grid_w + 1u) * (UOCR_LOCAL_GRID_QUERIES * grid_h);
}

static inline int uocr_sam_block_uses_global_attention(uint32_t block_index) {
    return block_index == 2u || block_index == 5u || block_index == 8u || block_index == 11u;
}

#endif /* UOCR_MODEL_CONSTANTS_H */
